#!/usr/bin/env python3
"""
Usage: python scan_appfunctions.py <apk_dir> <count> [--out results.json] [--csv results.csv] [--workers 8]
"""

import sys, zipfile, re, json, csv, argparse
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor, as_completed

# STRONG DEX needles (bytes)
STRONG_DEX = {
    b"AppFunctionInventory": "dex_inventory_generated", # AppFunctionInventory seems to be generated by the annotator. Strong signal from evidence
    b"appfunctions/schema/": "dex_schema_namespace", # from evidence (gallery3d)
    b"Landroidx/appfunctions/AppFunctionService;": "dex_service_androidx", # https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.3.2 literal Jetpack AppFunctionService class
    b"Landroidx/appfunctions/AppFunctionContext;": "dex_context_androidx", # literal Jetpack AppFunctionContext class
}

# WEAK DEX needles (bytes)
WEAK_DEX = {
    b"androidx/appfunctions": "dex_pkg_androidx", # General Jetpack AppFunctions package ref. Does not imply usage
    b"com/google/android/appfunctions": "dex_pkg_google", # Non Jetpack AppFunctions package ref (gallery3d). Does not imply usage
    b"Landroidx/appfunctions/AppFunction": "dex_annotation_appfunction", # Jetpack AppFunction string start, does not imply usage
    b"Landroidx/appfunctions/AppFunctionSerializable;": "dex_annotation_serializable", # https://developer.android.com/reference/androidx/appfunctions/AppFunctionSerializable
}

# Manifest strings (binary AXML string pool; matched as UTF-8 AND UTF-16LE)
MANIFEST_STRINGS = {
    "android.app.appfunctions.AppFunctionService": "manifest_service_action", # from evidence (gallery3d)
    "android.permission.BIND_APP_FUNCTION_SERVICE": "manifest_bind_permission", # permission, from docs and evidence
    "com.android.extensions.appfunctions": "manifest_uses_library", # library usage, from docs and evidence
}
MANIFEST_NEEDLES = {
    key: (s.encode("utf-8"), s.encode("utf-16-le")) for s, key in MANIFEST_STRINGS.items()
}

# Resource filename suffixes
STRONG_RES_SUFFIXES = {
    "app_functions.xml": "res_app_functions_xml", # from evidence (found in Samsung Notes)
    "app_function.xml": "res_app_function_xml", # from evidence (found explicitly in Samsung apps)
    "app_functions_v2.xml": "res_app_functions_v2_xml", # Jetpack library artifact (found in Samsung Gallery)
    "app_functions_schema.xsd": "res_app_functions_schema_xsd", # found in baseline AppFunctions app, does not appear to be mandatory, so a weak signal
}
WEAK_RES_SUFFIXES = {
    "app_metadata.xml": "res_app_metadata_xml", # found in baseline AppFunctions app, does not appear to be mandatory (natural language app descriptor), so a weak signal
}

DEX_NAME_RE = re.compile(r"classes\d*\.dex$")

STRONG_KEYS = [*STRONG_RES_SUFFIXES.values(), *MANIFEST_NEEDLES.keys(), *STRONG_DEX.values()]
WEAK_KEYS   = [*WEAK_RES_SUFFIXES.values(), *WEAK_DEX.values()]
SIGNAL_KEYS = [*STRONG_KEYS, *WEAK_KEYS]


def analyze_apk(apk_path_str: str) -> dict:
    apk_path = Path(apk_path_str)
    sigs = {k: False for k in SIGNAL_KEYS}
    result = {
        "apk": apk_path.name,
        "path": str(apk_path),
        "has_appfunctions": False,
        "weak_only": False,
        "signals": sigs,
        "error": None,
    }

    try:
        with zipfile.ZipFile(apk_path, "r") as z:
            manifest_name = None
            dex_entries = []

            for fileName in z.namelist():
                ln = fileName.lower()
                for suffix, key in STRONG_RES_SUFFIXES.items():
                    if ln.endswith(suffix):
                        sigs[key] = True
                for suffix, key in WEAK_RES_SUFFIXES.items():
                    if ln.endswith(suffix):
                        sigs[key] = True
                if ln == "androidmanifest.xml":
                    manifest_name = fileName
                elif DEX_NAME_RE.match(fileName):
                    dex_entries.append(fileName)

            if manifest_name:
                data = z.read(manifest_name)
                for key, (u8, u16) in MANIFEST_NEEDLES.items():
                    if u8 in data or u16 in data:
                        sigs[key] = True

            remaining = [*STRONG_DEX.items(), *WEAK_DEX.items()]
            for d in sorted(dex_entries):
                if not remaining:
                    break
                blob = z.read(d)
                still = []
                for needle, key in remaining:
                    if needle in blob:
                        sigs[key] = True
                    else:
                        still.append((needle, key))
                remaining = still

    except zipfile.BadZipFile:
        result["error"] = "bad_zip"
        return result
    except Exception as e:
        result["error"] = f"{type(e).__name__}: {e}"
        return result

    strong_hit = any(sigs[k] for k in STRONG_KEYS)
    weak_hit = any(sigs[k] for k in WEAK_KEYS)

    result["has_appfunctions"] = strong_hit
    result["weak_only"] = (not strong_hit) and weak_hit
    return result


def main():
    parser = argparse.ArgumentParser(description="Scan APKs for AppFunctions signals")
    parser.add_argument("apk_dir", help="Directory containing APK files")
    parser.add_argument("count", type=int, help="Max number of APKs to analyze")
    parser.add_argument("--out", default="results.json", help="Output JSON file (default: results.json)")
    parser.add_argument("--csv", default=None, help="Optional CSV summary output")
    parser.add_argument("--workers", type=int, default=8, help="Parallel workers (default: 8)")
    args = parser.parse_args()

    apks = sorted(Path(args.apk_dir).glob("*.apk"))[: args.count]
    if not apks:
        print(f"No APKs found in {args.apk_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Scanning {len(apks)} APKs with {args.workers} workers...")

    results = []
    positive = 0
    weak_only = 0

    with ProcessPoolExecutor(max_workers=args.workers) as pool:
        futures = {pool.submit(analyze_apk, str(apk)): apk for apk in apks}
        for i, future in enumerate(as_completed(futures), 1):
            r = future.result()
            results.append(r)
            if r["has_appfunctions"]:
                positive += 1
            elif r["weak_only"]:
                weak_only += 1
            if i % 100 == 0 or i == len(apks):
                print(f"  {i}/{len(apks)} done — {positive} strong, {weak_only} weak-only so far")

    results.sort(key=lambda x: x["apk"])

    summary = {
        "total_scanned": len(results),
        "with_appfunctions": positive,
        "weak_only": weak_only,
        "without_appfunctions": sum(1 for r in results if not r["has_appfunctions"] and not r["weak_only"]),
        "errors": sum(1 for r in results if r["error"]),
        "signal_counts": {k: sum(1 for r in results if r["signals"].get(k)) for k in SIGNAL_KEYS},
    }

    with open(args.out, "w") as f:
        json.dump({"summary": summary, "results": results}, f, indent=2)

    if args.csv:
        with open(args.csv, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["apk", "has_appfunctions", "weak_only", "error", *SIGNAL_KEYS])
            for r in results:
                writer.writerow([
                    r["apk"],
                    r["has_appfunctions"],
                    r["weak_only"],
                    r["error"] or "",
                    *[r["signals"].get(k, False) for k in SIGNAL_KEYS],
                ])

    print(f"\nDone. {positive}/{len(results)} APKs have strong AppFunctions signals "
          f"({weak_only} weak-only).")
    print("Signal breakdown (strong first):")
    for sig in STRONG_KEYS:
        print(f"  [Strong] {sig}: {summary['signal_counts'][sig]}")
    for sig in WEAK_KEYS:
        print(f"  [Weak] {sig}: {summary['signal_counts'][sig]}")
    print(f"\nFull results -> {args.out}")
    if args.csv:
        print(f"CSV summary  -> {args.csv}")


if __name__ == "__main__":
    main()